version: '3.2'

services:
  db:
    container_name: database
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - database-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'database'
    restart: unless-stopped

volumes:
  database-db-data:
