version: '3.2'

services:
  db:
    container_name: fakt-database
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - fakt-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'fakt-user'
      POSTGRES_PASSWORD: 'fakt-password'
      POSTGRES_DB: 'fakt'
    restart: unless-stopped

volumes:
  fakt-db-data:
