quarkus:
  http:
    root-path: /api

  datasource:
    db-kind: postgresql
    username: username
    password: password
    jdbc:
      url: jdbc:postgresql://localhost:5432/database

  hibernate-orm:
    database:
      generation: update

  rest-client:
    keycloak:
      url: ${app.idp.url}
      scope: jakarta.inject.Singleton

app:
  idp:
    url: https://auth.pausegarra.es/realms/principal
    client-id: client-id

mp:
  jwt:
    verify:
      publickey:
        location: ${app.idp.url}/protocol/openid-connect/certs
      issuer: ${app.idp.url}
      audience: ${app.id.client-id}
