version: '3.2'

services:
  fakt-api:
    container_name: fakt-api
    image: psegarra/fakt-api:${VERSION}
    ports:
      - "8080:8080"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/fakt
      - QUARKUS_DATASOURCE_USERNAME=${DB_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${DB_PASSWORD}